import { Country } from "@/types";

export const countries: Country[] = [
  { short: "AF", long: "Afghanistan", flag: "🇦🇫" },
  { short: "AL", long: "Albania", flag: "🇦🇱" },
  { short: "DZ", long: "Algeria", flag: "🇩🇿" },
  { short: "AD", long: "Andorra", flag: "🇦🇩" },
  { short: "AO", long: "Angola", flag: "🇦🇴" },
  { short: "AI", long: "Anguilla", flag: "🇦🇮" },
  { short: "AG", long: "Antigua and Barbuda", flag: "🇦🇬" },
  { short: "AR", long: "Argentina", flag: "🇦🇷" },
  { short: "AM", long: "Armenia", flag: "🇦🇲" },
  { short: "AW", long: "Aruba", flag: "🇦🇼" },
  { short: "AU", long: "Australia", flag: "🇦🇺" },
  { short: "AT", long: "Austria", flag: "🇦🇹" },
  { short: "AZ", long: "Azerbaijan", flag: "🇦🇿" },
  { short: "BS", long: "Bahamas", flag: "🇧🇸" },
  { short: "BH", long: "Bahrain", flag: "🇧🇭" },
  { short: "BD", long: "Bangladesh", flag: "🇧🇩" },
  { short: "BB", long: "Barbados", flag: "🇧🇧" },
  { short: "BY", long: "Belarus", flag: "🇧🇾" },
  { short: "BE", long: "Belgium", flag: "🇧🇪" },
  { short: "BZ", long: "Belize", flag: "🇧🇿" },
  { short: "BJ", long: "Benin", flag: "🇧🇯" },
  { short: "BM", long: "Bermuda", flag: "🇧🇲" },
  { short: "BT", long: "Bhutan", flag: "🇧🇹" },
  { short: "BO", long: "Bolivia", flag: "🇧🇴" },
  { short: "BA", long: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { short: "BW", long: "Botswana", flag: "🇧🇼" },
  { short: "BR", long: "Brazil", flag: "🇧🇷" },
  { short: "IO", long: "British Indian Ocean Territory", flag: "🇮🇴" },
  { short: "BN", long: "Brunei Darussalam", flag: "🇧🇳" },
  { short: "BG", long: "Bulgaria", flag: "🇧🇬" },
  { short: "BF", long: "Burkina Faso", flag: "🇧🇫" },
  { short: "BI", long: "Burundi", flag: "🇧🇮" },
  { short: "CV", long: "Cabo Verde", flag: "🇨🇻" },
  { short: "KH", long: "Cambodia", flag: "🇰🇭" },
  { short: "CM", long: "Cameroon", flag: "🇨🇲" },
  { short: "KY", long: "Cayman Islands", flag: "🇰🇾" },
  { short: "CF", long: "Central African Republic", flag: "🇨🇫" },
  { short: "TD", long: "Chad", flag: "🇹🇩" },
  { short: "CL", long: "Chile", flag: "🇨🇱" },
  { short: "CN", long: "China", flag: "🇨🇳" },
  { short: "CX", long: "Christmas Island", flag: "🇨🇽" },
  { short: "CC", long: "Cocos (Keeling) Islands", flag: "🇨🇨" },
  { short: "CO", long: "Colombia", flag: "🇨🇴" },
  { short: "KM", long: "Comoros", flag: "🇰🇲" },
  { short: "CD", long: "Congo, Democratic Republic of the", flag: "🇨🇩" },
  { short: "CG", long: "Congo, Republic of the", flag: "🇨🇬" },
  { short: "CK", long: "Cook Islands", flag: "🇨🇰" },
  { short: "CR", long: "Costa Rica", flag: "🇨🇷" },
  { short: "HR", long: "Croatia", flag: "🇭🇷" },
  { short: "CU", long: "Cuba", flag: "🇨🇺" },
  { short: "CW", long: "Curaçao", flag: "🇨🇼" },
  { short: "CY", long: "Cyprus", flag: "🇨🇾" },
  { short: "CZ", long: "Czech Republic", flag: "🇨🇿" },
  { short: "DK", long: "Denmark", flag: "🇩🇰" },
  { short: "DJ", long: "Djibouti", flag: "🇩🇯" },
  { short: "DM", long: "Dominica", flag: "🇩🇲" },
  { short: "DO", long: "Dominican Republic", flag: "🇩🇴" },
  { short: "EC", long: "Ecuador", flag: "🇪🇨" },
  { short: "EG", long: "Egypt", flag: "🇪🇬" },
  { short: "SV", long: "El Salvador", flag: "🇸🇻" },
  { short: "GQ", long: "Equatorial Guinea", flag: "🇬🇶" },
  { short: "ER", long: "Eritrea", flag: "🇪🇷" },
  { short: "EE", long: "Estonia", flag: "🇪🇪" },
  { short: "ET", long: "Ethiopia", flag: "🇪🇹" },
  { short: "FK", long: "Falkland Islands (Malvinas)", flag: "🇫🇰" },
  { short: "FO", long: "Faroe Islands", flag: "🇫🇴" },
  { short: "FJ", long: "Fiji", flag: "🇫🇯" },
  { short: "FI", long: "Finland", flag: "🇫🇮" },
  { short: "FR", long: "France", flag: "🇫🇷" },
  { short: "GF", long: "French Guiana", flag: "🇬🇫" },
  { short: "PF", long: "French Polynesia", flag: "🇵🇫" },
  { short: "TF", long: "French Southern Territories", flag: "🇹🇫" },
  { short: "GA", long: "Gabon", flag: "🇬🇦" },
  { short: "GM", long: "Gambia", flag: "🇬🇲" },
  { short: "GE", long: "Georgia", flag: "🇬🇪" },
  { short: "DE", long: "Germany", flag: "🇩🇪" },
  { short: "GH", long: "Ghana", flag: "🇬🇭" },
  { short: "GI", long: "Gibraltar", flag: "🇬🇮" },
  { short: "GR", long: "Greece", flag: "🇬🇷" },
  { short: "GL", long: "Greenland", flag: "🇬🇱" },
  { short: "GD", long: "Grenada", flag: "🇬🇩" },
  { short: "GP", long: "Guadeloupe", flag: "🇬🇵" },
  { short: "GU", long: "Guam", flag: "🇬🇺" },
  { short: "GT", long: "Guatemala", flag: "🇬🇹" },
  { short: "GG", long: "Guernsey", flag: "🇬🇬" },
  { short: "GN", long: "Guinea", flag: "🇬🇳" },
  { short: "GW", long: "Guinea-Bissau", flag: "🇬🇼" },
  { short: "GY", long: "Guyana", flag: "🇬🇾" },
  { short: "HT", long: "Haiti", flag: "🇭🇹" },
  { short: "HM", long: "Heard Island and McDonald Islands", flag: "🇭🇲" },
  { short: "VA", long: "Holy See (Vatican City State)", flag: "🇻🇦" },
  { short: "HN", long: "Honduras", flag: "🇭🇳" },
  { short: "HK", long: "Hong Kong", flag: "🇭🇰" },
  { short: "HU", long: "Hungary", flag: "🇭🇺" },
  { short: "IS", long: "Iceland", flag: "🇮🇸" },
  { short: "IN", long: "India", flag: "🇮🇳" },
  { short: "ID", long: "Indonesia", flag: "🇮🇩" },
  { short: "IR", long: "Iran, Islamic Republic of", flag: "🇮🇷" },
  { short: "IQ", long: "Iraq", flag: "🇮🇶" },
  { short: "IE", long: "Ireland", flag: "🇮🇪" },
  { short: "IM", long: "Isle of Man", flag: "🇮🇲" },
  { short: "JM", long: "Jamaica", flag: "🇯🇲" },
  { short: "JP", long: "Japan", flag: "🇯🇵" },
  { short: "JE", long: "Jersey", flag: "🇯🇪" },
  { short: "JO", long: "Jordan", flag: "🇯🇴" },
  { short: "KZ", long: "Kazakhstan", flag: "🇰🇿" },
  { short: "KE", long: "Kenya", flag: "🇰🇪" },
  { short: "KI", long: "Kiribati", flag: "🇰🇮" },
  { short: "KP", long: "Korea, Democratic People's Republic of", flag: "🇰🇵" },
  { short: "KR", long: "Korea, Republic of", flag: "🇰🇷" },
  { short: "KW", long: "Kuwait", flag: "🇰🇼" },
  { short: "KG", long: "Kyrgyzstan", flag: "🇰🇬" },
  { short: "LA", long: "Lao People's Democratic Republic", flag: "🇱🇦" },
  { short: "LV", long: "Latvia", flag: "🇱🇻" },
  { short: "LB", long: "Lebanon", flag: "🇱🇧" },
  { short: "LS", long: "Lesotho", flag: "🇱🇸" },
  { short: "LR", long: "Liberia", flag: "🇱🇷" },
  { short: "LY", long: "Libya", flag: "🇱🇾" },
  { short: "LI", long: "Liechtenstein", flag: "🇱🇮" },
  { short: "LT", long: "Lithuania", flag: "🇱🇹" },
  { short: "LU", long: "Luxembourg", flag: "🇱🇺" },
  { short: "MO", long: "Macao", flag: "🇲🇴" },
  {
    short: "MK",
    long: "Macedonia, the former Yugoslav Republic of",
    flag: "🇲🇰",
  },
  { short: "MG", long: "Madagascar", flag: "🇲🇬" },
  { short: "MW", long: "Malawi", flag: "🇲🇼" },
  { short: "MY", long: "Malaysia", flag: "🇲🇾" },
  { short: "MV", long: "Maldives", flag: "🇲🇻" },
  { short: "ML", long: "Mali", flag: "🇲🇱" },
  { short: "MT", long: "Malta", flag: "🇲🇹" },
  { short: "MH", long: "Marshall Islands", flag: "🇲🇭" },
  { short: "MQ", long: "Martinique", flag: "🇲🇶" },
  { short: "MR", long: "Mauritania", flag: "🇲🇷" },
  { short: "MU", long: "Mauritius", flag: "🇲🇺" },
  { short: "YT", long: "Mayotte", flag: "🇾🇹" },
  { short: "MX", long: "Mexico", flag: "🇲🇽" },
  { short: "FM", long: "Micronesia, Federated States of", flag: "🇫🇲" },
  { short: "MD", long: "Moldova, Republic of", flag: "🇲🇩" },
  { short: "MC", long: "Monaco", flag: "🇲🇨" },
  { short: "MN", long: "Mongolia", flag: "🇲🇳" },
  { short: "ME", long: "Montenegro", flag: "🇲🇪" },
  { short: "MS", long: "Montserrat", flag: "🇲🇸" },
  { short: "MA", long: "Morocco", flag: "🇲🇦" },
  { short: "MZ", long: "Mozambique", flag: "🇲🇿" },
  { short: "MM", long: "Myanmar", flag: "🇲🇲" },
  { short: "NA", long: "Namibia", flag: "🇳🇦" },
  { short: "NR", long: "Nauru", flag: "🇳🇷" },
  { short: "NP", long: "Nepal", flag: "🇳🇵" },
  { short: "NL", long: "Netherlands", flag: "🇳🇱" },
  { short: "NC", long: "New Caledonia", flag: "🇳🇨" },
  { short: "NZ", long: "New Zealand", flag: "🇳🇿" },
  { short: "NI", long: "Nicaragua", flag: "🇳🇮" },
  { short: "NE", long: "Niger", flag: "🇳🇪" },
  { short: "NG", long: "Nigeria", flag: "🇳🇬" },
  { short: "NU", long: "Niue", flag: "🇳🇺" },
  { short: "NF", long: "Norfolk Island", flag: "🇳🇫" },
  { short: "MP", long: "Northern Mariana Islands", flag: "🇲🇵" },
  { short: "NO", long: "Norway", flag: "🇳🇴" },
  { short: "OM", long: "Oman", flag: "🇴🇲" },
  { short: "PK", long: "Pakistan", flag: "🇵🇰" },
  { short: "PW", long: "Palau", flag: "🇵🇼" },
  { short: "PS", long: "Palestine", flag: "🇵🇸" },
  { short: "PA", long: "Panama", flag: "🇵🇦" },
  { short: "PG", long: "Papua New Guinea", flag: "🇵🇬" },
  { short: "PY", long: "Paraguay", flag: "🇵🇾" },
  { short: "PE", long: "Peru", flag: "🇵🇪" },
  { short: "PH", long: "Philippines", flag: "🇵🇭" },
  { short: "PN", long: "Pitcairn", flag: "🇵🇳" },
  { short: "PL", long: "Poland", flag: "🇵🇱" },
  { short: "PT", long: "Portugal", flag: "🇵🇹" },
  { short: "PR", long: "Puerto Rico", flag: "🇵🇷" },
  { short: "QA", long: "Qatar", flag: "🇶🇦" },
  { short: "RE", long: "Réunion", flag: "🇷🇪" },
  { short: "RO", long: "Romania", flag: "🇷🇴" },
  { short: "RU", long: "Russian Federation", flag: "🇷🇺" },
  { short: "RW", long: "Rwanda", flag: "🇷🇼" },
  { short: "BL", long: "Saint Barthélemy", flag: "🇧🇱" },
  {
    short: "SH",
    long: "Saint Helena, Ascension and Tristan da Cunha",
    flag: "🇸🇭",
  },
  { short: "KN", long: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { short: "LC", long: "Saint Lucia", flag: "🇱🇨" },
  { short: "MF", long: "Saint Martin (French part)", flag: "🇲🇫" },
  { short: "PM", long: "Saint Pierre and Miquelon", flag: "🇵🇲" },
  { short: "VC", long: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  { short: "WS", long: "Samoa", flag: "🇼🇸" },
  { short: "SM", long: "San Marino", flag: "🇸🇲" },
  { short: "ST", long: "Sao Tome and Principe", flag: "🇸🇹" },
  { short: "SA", long: "Saudi Arabia", flag: "🇸🇦" },
  { short: "SN", long: "Senegal", flag: "🇸🇳" },
  { short: "RS", long: "Serbia", flag: "🇷🇸" },
  { short: "SC", long: "Seychelles", flag: "🇸🇨" },
  { short: "SL", long: "Sierra Leone", flag: "🇸🇱" },
  { short: "SG", long: "Singapore", flag: "🇸🇬" },
  { short: "SX", long: "Sint Maarten (Dutch part)", flag: "🇸🇽" },
  { short: "SK", long: "Slovakia", flag: "🇸🇰" },
  { short: "SI", long: "Slovenia", flag: "🇸🇮" },
  { short: "SB", long: "Solomon Islands", flag: "🇸🇧" },
  { short: "SO", long: "Somalia", flag: "🇸🇴" },
  { short: "ZA", long: "South Africa", flag: "🇿🇦" },
  {
    short: "GS",
    long: "South Georgia and the South Sandwich Islands",
    flag: "🇬🇸",
  },
  { short: "SS", long: "South Sudan", flag: "🇸🇸" },
  { short: "ES", long: "Spain", flag: "🇪🇸" },
  { short: "LK", long: "Sri Lanka", flag: "🇱🇰" },
  { short: "SD", long: "Sudan", flag: "🇸🇩" },
  { short: "SR", long: "Suriname", flag: "🇸🇷" },
  { short: "SJ", long: "Svalbard and Jan Mayen", flag: "🇸🇯" },
  { short: "SZ", long: "Swaziland", flag: "🇸🇿" },
  { short: "SE", long: "Sweden", flag: "🇸🇪" },
  { short: "CH", long: "Switzerland", flag: "🇨🇭" },
  { short: "SY", long: "Syrian Arab Republic", flag: "🇸🇾" },
  { short: "TW", long: "Taiwan, Province of China", flag: "🇹🇼" },
  { short: "TJ", long: "Tajikistan", flag: "🇹🇯" },
  { short: "TZ", long: "Tanzania, United Republic of", flag: "🇹🇿" },
  { short: "TH", long: "Thailand", flag: "🇹🇭" },
  { short: "TL", long: "Timor-Leste", flag: "🇹🇱" },
  { short: "TG", long: "Togo", flag: "🇹🇬" },
  { short: "TK", long: "Tokelau", flag: "🇹🇰" },
  { short: "TO", long: "Tonga", flag: "🇹🇴" },
  { short: "TT", long: "Trinidad and Tobago", flag: "🇹🇹" },
  { short: "TN", long: "Tunisia", flag: "🇹🇳" },
  { short: "TR", long: "Turkey", flag: "🇹🇷" },
  { short: "TM", long: "Turkmenistan", flag: "🇹🇲" },
  { short: "TC", long: "Turks and Caicos Islands", flag: "🇹🇨" },
  { short: "TV", long: "Tuvalu", flag: "🇹🇻" },
  { short: "UG", long: "Uganda", flag: "🇺🇬" },
  { short: "UA", long: "Ukraine", flag: "🇺🇦" },
  { short: "AE", long: "United Arab Emirates", flag: "🇦🇪" },
  { short: "GB", long: "United Kingdom", flag: "🇬🇧" },
  { short: "US", long: "United States", flag: "🇺🇸" },
  { short: "UM", long: "United States Minor Outlying Islands", flag: "🇺🇲" },
  { short: "UY", long: "Uruguay", flag: "🇺🇾" },
  { short: "UZ", long: "Uzbekistan", flag: "🇺🇿" },
  { short: "VU", long: "Vanuatu", flag: "🇻🇺" },
  { short: "VE", long: "Venezuela, Bolivarian Republic of", flag: "🇻🇪" },
  { short: "VN", long: "Viet Nam", flag: "🇻🇳" },
  { short: "VG", long: "Virgin Islands, British", flag: "🇻🇬" },
  { short: "VI", long: "Virgin Islands, U.S.", flag: "🇻🇮" },
  { short: "WF", long: "Wallis and Futuna", flag: "🇼🇫" },
  { short: "EH", long: "Western Sahara", flag: "🇪🇭" },
  { short: "YE", long: "Yemen", flag: "🇾🇪" },
  { short: "ZM", long: "Zambia", flag: "🇿🇲" },
  { short: "ZW", long: "Zimbabwe", flag: "🇿🇼" },
];
